# Generated by Django 2.0.3 on 2018-04-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('author', models.CharField(max_length=40, verbose_name='作者')),
            ],
        ),
    ]
