# Generated by Django 2.0.3 on 2018-04-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(default=1234, max_length=30, verbose_name='标签'),
            preserve_default=False,
        ),
    ]
